added ports 4200-42020 on docker-compose.yml and itest-docker-copose.yml
tabordasolutions/nics-docker pull request #1
Opened 2017-04-06 21:23 UTC by irodriguez93

This is to allow the AVL's to send information from Proxy to Emapi and to allow the rules for iptables to work. The yml file now references a new image that was pushed to ECR. The image is preconfigured with iptables.

2017-04-06 21:25 UTC, DreamWver approved these changes

2017-04-07 16:08 UTC, comeara requested changes
I don't think this PR is going to get you where you want to go. Ping me in Slack and we can discuss your goals and how to approach the changes.

2017-04-07 16:08 UTC, comeara commented on docker-compose.yml
> +      - "8085:80"
Why does this port need to change?

2017-04-07 16:08 UTC, comeara commented on docker-compose.yml
> +<<<<<<< HEAD
These are merge conflicts that you committed. This file is not valid YAML.

2017-04-07 16:08 UTC, comeara commented on docker-compose.yml
> +      - "42000-42020"
I don't think this is going to get you where you want to go. There is nothing listening on those ports in the EM-API container. Also, when we add the AVL processors, they will be running in a different container.

2017-04-07 17:09 UTC, irodriguez93 commented on docker-compose.yml
> +<<<<<<< HEAD
Yeah, it looks like the merge got screwed up. Let's discuss if you are available.

2017-04-07 17:14 UTC, closed without merging