Referencing new pre-configured nics/nicsweb:dev-configured image
tabordasolutions/nics-docker pull request #3
Opened 2017-04-24 23:27 UTC by DreamWver

Created new images for proxy and nicsweb with embedded tls certs.

2017-04-28 14:24 UTC, comeara requested changes
It looks like Apache is still trying to redirect to port 3443. I think the port change requires a corresponding change to Apache.

2017-04-28 14:50 UTC, DreamWver commented
Good Catch. I'll make the change to the nics.conf.sample over on nics-www.

2017-05-05 14:09 UTC, comeara commented on docker-compose.yml
>        - "3000:80"
I suggest you also move http to 80 rather than 3000 if you're going to use 443 for https.

2017-05-05 14:11 UTC, comeara commented
I retested this today and it is still broken due to the fact that the proxy:dev-configured and web:latest images have not been updated.

2017-05-12 17:31 UTC, DreamWver commented
I updated the proxy:dev-configured and web:latest images. And changed the port mapping on the proxy as you requested. Also made one more port mapping change that was plaguing us due to a service conflict.

2017-05-12 18:00 UTC, sneha-nagole approved these changes

2017-05-16 04:14 UTC, comeara approved these changes

2017-05-16 04:25 UTC, merged